language: android

android:
  components:
    - build-tools-21.1.2
    - extra-android-m2repository
    - extra-google-m2repository
    - android-21
    - android-18
  licenses:
    - android-sdk-license-5be876d5

jdk:
  - oraclejdk7

script:
  - ./gradlew clean check
  
sudo: false

cache:
  directories:
    - $HOME/.gradle
