language: android

android:
  components:
    - build-tools-21.1.1
    - extra-android-m2repository
    - extra-google-m2repository
    - android-21
  licenses:
    - android-sdk-license-5be876d5

jdk:
  - oraclejdk7
  - oraclejdk8
  
script:
  - ./gradlew clean check
  
sudo: false

cache:
  directories:
    - $HOME/.gradle
