language: android

android:
  components:
    - build-tools-21.1.2
    - extra-android-m2repository
    - extra-google-m2repository
    - android-21
  licenses:
    - android-sdk-license-5be876d5

jdk:
  - oraclejdk7

env:
  global:
    - secure: "UqqtEIUDUncVl8u6ghm9z9unzqd0vtvLJtPDgsUbN8aM6YI8cwXpy6zZp2Vwk0I3LB6GzWNY0UJhevna8hujwQLCXKGlgOui1ZJ1UTseL9pWNvl9eOjq2UJCOJCuNK9BKXe1vteCVgCevFsWhDNMnSa6MPoQi1e4R8e3fyQXyBw="

script:
  - ./gradlew clean check jacocoTestReport
  
sudo: false

cache:
  directories:
    - $HOME/.gradle

after_success:
- ./gradlew coveralls